config/routes.rb
Details::Application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

   root 'customers#index'

  
     resources :customers do
     resources :orders
     end
     resources :doctors
     resources :patients
     resources :suppliers

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient
end

app/models/create_join_table_customer_order.rb
class CreateJoinTableCustomerOrder < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_user!, :except => :index
  def new
    @customer=Customer.new
  end
  
  def create
    @customer=Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
    
  end
  
  def show
  #raise params[:id].inspect
  @customer=Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
   
    if @customer.update(params[:customer].permit(:name, :description))
      redirect_to @customer
    else
      render 'edit'
    end
  end
  
  def destroy
  @customer = Customer.find(params[:id])
  @customer.destroy
 
  redirect_to customers_path
end
  
  def index
    @customers=Customer.all
  end
  
  private
  def customer_params
    params.require(:customer).permit(:name, :description)
  end
  
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def new
    @doctor=Doctor.new
  end
  
  def create
    @doctor=Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor
    else
      render 'new'
    end
  end
  
  def show
  @doctor=Doctor.find(params[:id])
  #raise @doctor.patients.inspect
  @patients=@doctor.patients
  #@patients=Patient.find(:all, :conditions => ["doctor_id = ?", @doctor.id])
  #@patients=Patient.where(:doctor_id => @doctor.id)
  end
  
  def index
    @doctors=Doctor.all
  end
  
  private
  def doctor_params
    params.require(:doctor).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @customer = Customer.find(params[:customer_id])
    @order = @customer.orders.create(params[:order].permit(:name, :details))
    redirect_to customer_path(@customer)
  end
  
  def destroy
    @customer = Customer.find(params[:customer_id])
    @order = @customer.orders.find(params[:id])
    @order.destroy
    redirect_to customer_path(@customer)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @patient=Patient.new
  end
  
  def create
    @patient=Patient.new(patient_params)
    if @patient.save
      ids = params['patient']['doctor_ids']
      ids.each do |id|
        doct = Doctor.find(id)
        @patient.doctors << doct 
      end
      redirect_to @patient
    else
      render 'new'
    end
  end
  
  def show
    #Doctor.find(params['patient']['doctor_ids'][0]).patients << Patient.find(params[:id])
    @patient=Patient.find(params[:id])
    @doctors=@patient.doctors
  end
  
  def index
    @patients=Patient.all
  end
  
  
  def edit
    raise params.inspect
    @patient = Patient.find(params[:id])
  end
  
  def update
    @patient = Patient.find(params[:id])
    if @patient.update(params[:patient].permit(:name))
      ids = params['patient']['doctor_ids']
      ids.each do |id|
        doct = Doctor.find(id)
        if !@patient.doctors.exists?(id)
          @patient.doctors << doct 
        end
        (1.. Doctor.find(:all).length).each do |doctor|
          if !ids.include?(doctor.to_s)
            if @patient.doctors.exists?(doctor)
              @patient.doctors.destroy(doctor)
            end
          end
        end
      end
      redirect_to @patient
    else
      render 'edit'
    end
  end
  
  
  private
    def patient_params
      params.require(:patient).permit(:name)
    end    
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  def create
    render text: params[:supplier].inspect
  end
  
  def new
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, url: customer_path(@customer.id) do |f| %>

<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Details</h1>

<%= render 'form' %>

<%= link_to 'customers list', customers_path %>

app/views/customers/index.html.erb
<h1>Hello Customers</h1>
<%= link_to 'New customer', new_customer_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.description %></td>
      <td><%= link_to 'show', customer_path(customer) %></td>
      <td><%= link_to 'edit', edit_customer_path(customer) %></td>
      <td><%= link_to 'Destroy', customer_path(customer),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/customers/new.html.erb
<h2>New Customer</h2>

<%= render 'form' %>

<%= link_to 'customers list', customers_path %>

app/views/customers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @customer.description %>
</p>

<h2>Orders</h2>
<% @customer.orders.each do |order| %>
  <p>
    <strong>Order:</strong>
    <%= order.name %>
  </p>
 
  <p>
    <strong>details:</strong>
    <%= order.details %>
  </p>
  
  
  <p>
  <%= link_to 'Destroy Order', [order.customer, order],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>


<h2>Add Orders</h2>
<%= form_for([@customer, @customer.orders.build]) do |f|%>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'customers list', customers_path %><br>
<%= link_to 'edit', edit_customer_path %>

app/views/doctors/index.html.erb
<h2>List of Doctors</h2>
<%= link_to 'New Doctor', new_doctor_path %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.name %></td>
      <td><%= link_to 'show', doctor_path(doctor) %></td>
      <td><%#= link_to 'edit', edit_customer_path(customer) %></td>
      <td><%#= link_to 'Destroy', customer_path(customer),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/doctors/new.html.erb
<h2>Doctor</h2>

<% if @doctor.errors.any? %>
  <div id="errorExplanation">
  <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited Doctor from being saved:</h2>
  <ul>
  <% @doctor.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>

<%= form_for @doctor, url: doctor_path(@doctor.id) do |f| %>
<p>
  <%= f.label "Doctor's name"  %><br>
  <%= f.text_field :name %>
</p>



<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'Doctors list', doctors_path %>

app/views/doctors/show.html.erb
<p>
  <strong>Doctor's Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Patients:</strong>
  <% if @patients.exists? %>
    <% @patients.each do |patient| %>
    <%= patient.name %>,
    <% end %>
  <% else %>
    nil
  <% end %>
</p>

<%= link_to 'Doctors list', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Details</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>


<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%=link_to "Sign Out", destroy_user_session_path %>
  <% else %>
    <%=link_to "Sign up", new_user_registration_path %> or <%=link_to "Sign in", new_user_session_path %>
  <% end %>
</div>
<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/patients/edit.html.erb
<h2>Editing Patient Details</h2>
<%= form_for @patient, url: patient_path(@patient.id) do |f| %>
<p>
  <%= f.label 'Patient name:' %><br>
  <%= f.text_field :name %>
</p>
<strong><%= f.label 'Select Doctors:' %></strong><br>
<% for doctor in Doctor.find(:all) %>
<div>
  <%= check_box_tag "patient[doctor_ids][]", doctor.id, @patient.doctors.include?(doctor) %>
  <%= doctor.name %>
</div>
<% end %>

<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'BACK', patients_path %>

app/views/patients/index.html.erb
<h2>List of Patients</h2>
<%= link_to 'New Patient', new_patient_path %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.name %></td>
      <td><%= link_to 'show', patient_path(patient) %></td>
      <td><%= link_to 'edit', edit_patient_path(patient) %></td>
      <td><%#= link_to 'Destroy', customer_path(customer),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/patients/new.html.erb
<h2>New Patient</h2>

<% if @patient.errors.any? %>
  <div id="errorExplanation">
  <h2><%= pluralize(@patient.errors.count, "error") %> prohibited Patient from being saved:</h2>
  <ul>
  <% @patient.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>


<%= form_for @patient, url: patient_path(@patient.id) do |f| %>
<p>
  <%= f.label 'Patient name:' %><br>
  <%= f.text_field :name %>
</p>
<strong><%= f.label 'Select Doctors:' %></strong><br>
<% for doctor in Doctor.find(:all) %>
<div>
  <%= check_box_tag "patient[doctor_ids][]", doctor.id, @patient.doctors.include?(doctor) %>
  <%= doctor.name %>
</div>
<% end %>

<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'list', patients_path %>

app/views/patients/show.html.erb
<p>
  <strong>Patient Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Doctors:</strong>
  <% @doctors.each do |doctor| %>
   <%= doctor.name %>,
  <% end %>
</p>

<%= link_to 'list', patients_path %>
<%= link_to 'edit', edit_patient_path %>

app/views/suppliers/new.html.erb
<h2>New Supplier</h2>

<%= form_for :supplier, url: suppliers_path do |f| %>
  <p>
    <%= f.label 'Supplier Name:' %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>